#!/usr/bin/env bash
# vim: et sw=4 ts=4:

set -e
set -x
set -u

set -o pipefail

urlbasehtml=http://alpine.freeiz.com/alpine/info
urlbasepatch=http://alpine.freeiz.com/alpine/patches/alpine-2.21

for patch in \
    colortext \
    compose \
    count \
    fancy \
    fillpara \
    longurl \
    maildir \
    rules \
    tome
do
    curl --fail -s -O $urlbasehtml/$patch.html
    curl --fail -s $urlbasepatch/$patch.patch.gz | gzip -d > $patch.patch
done

curl --fail -s http://alpine.freeiz.com/alpine/info/courier.html > maildir-courier.html

